version: '3'

services:
  laravel:
    container_name: irinbridge
    restart: always
    image: 905666888987.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
    volumes:
      # - laravel:/var/www/html
      - admin_assests:/var/www/html/public/admin_assets/images
      - storage:/var/www/html/storage
      - ./irinbridge/log:/var/log/apache2
    ports:
      - "80:80"

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
volumes:
  admin_assests:
  storage:
  redis:
  # laravel: