version: '3'

services:
  tests:
    container_name: tests
    image: laravel-mongodb:latest
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    logging:
      driver: none

volumes:
  mongodb:
  mongoconfig: