version: '3'

services:
  tests:
    container_name: irinbridge
    restart: always
    image: 905666888987.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
    volumes:
      # - laravel:/var/www/html
      - ./irinbridge/log:/var/log/apache2
    ports:
      - "443:443"

# volumes:
#   laravel: